### ISSUE TITLE
Template per esportazione

### ISSUE THREAD

**Issue by Guray00** [coccocarmiano/polito-rust-notes#2]
Volevo cominciare ringraziandoti per gli appunti! Negli ultimi mesi ho lavorato a un template per l'esportazione di sbobine scritte in markdown (sono anche io un grande fan) a pdf, web (html) e epub, potrebbe essere molto utile per questo o progetti futuri. 

Ti lascio di seguito qualche link per dare un'occhiata:

- [Repository del template](https://github.com/guray00/template_lectures)
- [Esempi reali (mie sbobine)](https://lectures.mlampis.dev/)

Spero possa essere utile, buona giornata!

PS: se mi dai l'autorizzazione sto valutando di utilizzare i tuoi appunti come base di partenza per il corso di quest'anno da ricaricare nella mia repo :P

**Comment by coccocarmiano** [comment]
Ciao! Anzitutto grazie :)

In realtà non sono interessato perché il processo di export/compilazione è stato raffazzonato alla buona giusto per pubblicarle prima dell'esame. 
Se avessi avuto la voglia di fare qualcosa di decente probabilmente mi sarei messo a impostare delle Action in modo da
avere solo i `.md` in upload col resto generato al momento del push, appunto.

Detto ciò sentiti libero di utilizzarle come base tenendo a mente che:
- Ci sono degli errori (non potrebbero esserci: ci sono)
- Avendo imparato meglio il linguaggio dopo l'esame ed essendo lui cambiato nei mesi dopo, probabilmente alcuni esempi sono di gran lunga migliorabili
